### ISSUE TITLE
NUXT_SHOPIFY_STOREFRONT environment variable issue (local and cloud flare pages)

### ISSUE THREAD

**Issue by egant** [rylanharper/Nitrogen#8]
👋 Hello @rylanharper

a big thank you for making and sharing Nitrogen. it's a more complete starter template than what I could find for Sveltekit or Astro and now has me looking at Nuxt!

i had two small hiccups getting Nitrogen up and running, one local and one with cloudflare pages.

deploying locally   -   .env value for NUXT_SHOPIFY_STOREFRONT seems to take only a hostname value not a fully qualified domain name. i found most storefront templates make me paste a FQDN for their storefront api value (NUXT_SHOPIFY_STOREFRONT) into my .env file but Nitrogen only needs the hostname. could the way this is working cause problems for people who test or deploy against a Shopify store that has a custom domain configured?

deploying on Cloudflare Pages   -   environment variables seemed not to work - changing useRuntimeConfig() to useRuntimeConfig(event) in /server/api/shopify.ts [[9,32]] resolved this. I tried to deploy to Cloudflare Pages and found that the environment variables for the project were not picked up, so Nitrogen worker spat out a bunch of 403 errors. I found this https://nitro.build/deploy/providers/cloudflare#environment-variables and changed to useRuntimeConfig(event) and when redeploying it worked.

want a docs PR to update to readme ? or faq / wiki  - happy to help if I can?

**Comment by rylanharper** [comment]
Hey @egant!

Wow, thank you so much for trying out this template. A lot of work has gone into this project, so it's incredibly valuable to hear your feedback—whether it's suggestions, improvement, or clarifications. Also, glad this project is bringing you over to the Nuxt side of things! It’s my favorite framework by far in terms of DX (though I’ve used Svelte extensively in the past too).

Let me address your questions.. 

### 1. Storefront Hostname

No, adding the storefront hostname won’t affect testing or deploying your Shopify store in any way. This template connects directly to Shopify's GraphQL Storefront API through the `/server/api/shopify.ts` proxy using the URL:
`https://${options.storefront}.myshopify.com/api/${options.apiVersion}/graphql.json`. Each Shopify store has a unique hostname (often to the dismay of anyone hoping for a specific shop admin name lol), and no two stores share the same hostname. This is a safe and easy way to connect to the Storefront API.

### 2. Cloudflare Pages Issue

We shouldn’t need to add the `event` flag when using `useRuntimeConfig()`. This function simply retrieves the runtime configuration variables defined in `nuxt.config`. However, since I’m not familiar with Cloudflare Pages, this might be necessary in your case.

Can you do me a favor? What happens when you add in your environment variables manually in the `nuxt.config` like this:

```
runtimeConfig: {
  shopify: {
    storefront: process.env.NUXT_SHOPIFY_STOREFRONT ?? '',
    accessToken: process.env.NUXT_SHOPIFY_ACCESS_TOKEN ?? '',
    apiVersion:process.env.NUXT_SHOPIFY_API_VERSION ??  '2024-07'
  }
},
```
Do you have a successful deploy (without adding in the `event` to the `useRuntimeConfig()`)? 

I am asking this because I received a PR from Daniel Roe (one of Nuxt’s core team members) recommending the removal of inline `process.env` variables in `runtimeConfig`, as Nuxt automatically detects variables prefixed with `NUXT_`. While this approach worked more me, it’s possible that Cloudflare is handling environment variables differently. Let me know if adding in the environment variables manually changes anything.

---

### PRs and Documentation Updates

Let’s hold off on PRs or updates to the documentation until we’ve tested this further. I’m also in the process of adding a few more Shopify-specific components and rewriting a significant portion of the docs to reflect these changes.

This project is still a WIP (though it’s already quite stable), and I plan to roll out updates and new features regularly. My goal is to make this the go-to starting point for Nuxt developers building headless Shopify storefronts.

**Comment by rylanharper** [comment]
So following up on this (after looking into the issue a bit more), I actually think adding in the `event` may be needed for Cloudflare. It doesnt seem to affect any other deployments so adding in `useRuntimeConfig(event)` is safe to add here, although I haven't tested it on live just yet.

**Comment by egant** [comment]
I removed event from the useRuntimeConfig() in /server/api/shopify.ts  and added the variables to nuxt.config and it deployed on Cloudflare Pages and also works locally without issue for me.

So, If the proxy will always use the URL : https://${options.storefront}.myshopify.com/api/${options.apiVersion}/graphql.json 
I guess that means that shopify stores remain accessible via their STORE.myshopify.com FQDN even after a customized domain is assigned? 

Happy to try my hand  at a small PR... it would be the least I could do to show appreciation for all you have done ( btw, I'm a grape farmer in Bordeaux, France) so you might want to double check it !

**Comment by rylanharper** [comment]
@egant Glad to hear it's working when you manually enter the environment variables! Could you try clearing your cookies and testing the cart on live production? Also, refresh the page to confirm if the cart state persists.

Yes, you are correct—every Shopify store has a unique `.myshopify` domain that's always accessible, regardless of any custom domain changes. This domain is primarily tied to the admin/dashboard functionality.

On second thought, no need for a PR. I will add back in the `process.env` variables within the `nuxt.config`, as I like how this displays anyways (just seems to make more sense passing the environment variables in the config). 

Haha, that’s awesome that you’re a grape farmer! I am sure the grapes/wine tastes spectacular. Its actually pretty unique you have a diverse set of skills being a farmer AND a developer 🍷

Let me know what you find after clearing the cookies and testing the site. If everything runs smooth, I'll just add those variables into the config and push those changes. Again, I really appreciate the feedback about Cloudflare—I wouldn’t have known this was an issue otherwise.

**Comment by egant** [comment]
Cookies cleared and cart working. Page refreshes without issue too.

**Comment by rylanharper** [comment]
Great! I've made some updates to this template based on our discussion here..

The first is that I added the `process.env` variables back into the `nuxt.config` to handle deploying with Cloudflare Pages. The second is that I reconfigured the `NUXT_SHOPIFY_STOREFRONT` to take in the full `.myshopify` url, like you had mentioned earlier. This actually closer aligns with what is seen on the official [Storefront API Client](https://www.npmjs.com/package/@shopify/storefront-api-client). I've updated the documentation to reflect this as well (along with other doc updates). 

Again, I really appreciate you taking the time to post this issue. If you have any other issues, feel free to post them here or in the discussions tab and I'll take a look:)

Great! I’ve made some updates to this template based on our discussion:

1 .Reintroduced `process.env` variables in `nuxt.config` to ensure smooth deployment with Cloudflare Pages.
2. Updated the `NUXT_SHOPIFY_STOREFRONT` variable to accept the full `.myshopify` URL, aligning it more closely with the official [Storefront API Client](https://www.npmjs.com/package/@shopify/storefront-api-client).
I’ve also updated the documentation to reflect these changes, along with other improvements.

Again, thank you for raising this issue! If you run into anything else, feel free to post here or in the discussions tab—I’d be happy to help out :)

**Comment by egant** [comment]
> .... I’ve also updated the documentation to reflect these changes, along with other improvements.

Hi @rylanharper , In the updated README.md you have 
"NUXT_SHOPIFY_STOREFRONT=**http**://your-shop-name.myshopify.com"
I found that using http prevents the login page and the cart from working correctly. Changing to https works.
